### ISSUE TITLE
Error when running scripts/alignment.py with python 3.6

### ISSUE THREAD

**Issue by Abayomi-Olabode** [CoVaRR-NET/duotang#32]
Error 
```
[2022-04-14T18:42:40.959670] loading metadata
Traceback (most recent call last):
  File "scripts/alignment.py", line 244, in <module>
    metadata = load_metadata(args.metadata)
  File "scripts/alignment.py", line 164, in load_metadata
    yearweek = (dt.year, dt.isocalendar().week)
AttributeError: 'tuple' object has no attribute 'week'
```

Fix
Changing ```yearweek = (dt.year, dt.isocalendar().week)``` to ```yearweek = (dt.year, dt.isocalendar()[1])``` fixes the problem

**Comment by ArtPoon** [comment]
@Abayomi-Olabode did you push your fix to `dev`?  I'd like to close this issue.

**Comment by Abayomi-Olabode** [comment]
I just did

**Comment by ArtPoon** [comment]
Thanks @Abayomi-Olabode
